# Wheter you logged in with pyTwitchAPI before
"PyTwitchLoggedInBefore": True
# Whether you want to see debug messages in the console
"ShowDebugMessages": False
# Whether it is a Holiday or not
# Holiday Mode disables the auto logoff after a certain time of day.
# It does not have to be an actual holiday, if you do not want this to be enabled just set it to False.
# This can be set with a chat command
"IsHoliday": False
# When to automatically log off Moderators.
# It is recomnmended to set this to 5 minutes before your stream normally ends.
# This is disabled in Holiday Mode
# [Format]: "HH:MM" in 24-hour time
"AutoLogoffTime": "20:55"
# Whether to use the logged love scores.
# If you disable this, the love scores will be random every time someone uses the !love command.
"UseLoggedLoveScores": True
# Whether to look for updates on startup
"CheckForUpdatesOnStartup": True
# Wheter to enable chat commands
"UseChatCommands": True
# The file in which the keys and tokens are stored
# This has to be an absolute path, including the Drive Letter on Windows Systems and the file name.
"KeyFile": "C:/Users/DerFriese/Moderation-Tracker/keys.env"