[SETTINGS]
CurrentVersion = 0.17.1
# Which Channel to track on.
TargetChannel = Friesenjunge226
# Whether you want to see debug messages in the console
ShowDebugMessages = False
# Whether it is a Holiday or not
# Holiday Mode disables the auto logoff after a certain time of day.
# It does not have to be an actual holiday, if you do not want this to be enabled just set it to False.
# This can be set with a chat command
IsHoliday = False
# When to automatically log off Moderators.
# It is recomnmended to set this to 5 minutes before your stream normally ends.
# This is disabled in Holiday Mode
# [Format] = "HH:MM" in 24-hour time
AutoLogoffTime = 20:55
# Whether to use the logged love scores.
# If you disable this, the love scores will be random every time someone uses the !love command.
UseLoggedLoveScores = True
#Whether to play sound efects on messages
PlayMessageSoundEffects = True
# Whether to look for updates on startup
CheckForUpdatesOnStartup = True 
# If checking for updates = The Website to check for updates on
UpdateCheckURL = https://raw.githubusercontent.com/Friesenjunge226/Moderation-Tracker/refs/heads/main/config.conf
# Wheter to enable chat commands
UseChatCommands = True
# The file in which the love scores are stored
LoveScoreFile = love_scores.txt
# The interval in seconds in which the bot checks if moderators have to be logged off.
# In seconds
CheckInterval = 5
# List of users to be monitored
# [Format] = ["user1","user2","user3",...]
WatchedModerators = ["mo_ju_rsck","yinnox98_live","meliorasisback","friesenjunge226"]
# Users to be excluded from tracking e.g. Bots
# This list is probably complete, but if you use other bots, you can add them here.
# [Format] = ["user1","user2","user3",...]
BotNames = [TARGET_CHANNEL,"streamelements","moobot","nightbot","wizebot","ankhbot","phantombot","coebot","vercix","kappa_genius","streamlabs","streamloots"]
# Location of the keys.env file for Twitch API credentials
# Look in the README for more information on how to set up the keys.env file
KeyFile = keys.env